/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashSettingsRouteImport } from './routes/_dash/settings'
import { Route as DashIncidentsRouteImport } from './routes/_dash/incidents'
import { Route as DashDashboardRouteImport } from './routes/_dash/dashboard'
import { Route as DashAlertsRouteImport } from './routes/_dash/alerts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashIncidentsRoute = DashIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertsRoute = DashAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof DashAlertsRoute
  '/dashboard': typeof DashDashboardRoute
  '/incidents': typeof DashIncidentsRoute
  '/settings': typeof DashSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof DashAlertsRoute
  '/dashboard': typeof DashDashboardRoute
  '/incidents': typeof DashIncidentsRoute
  '/settings': typeof DashSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dash/alerts': typeof DashAlertsRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/incidents': typeof DashIncidentsRoute
  '/_dash/settings': typeof DashSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/alerts'
    | '/dashboard'
    | '/incidents'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/alerts'
    | '/dashboard'
    | '/incidents'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/register'
    | '/_dash/alerts'
    | '/_dash/dashboard'
    | '/_dash/incidents'
    | '/_dash/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/incidents': {
      id: '/_dash/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof DashIncidentsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alerts': {
      id: '/_dash/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashAlertsRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAlertsRoute: typeof DashAlertsRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashIncidentsRoute: typeof DashIncidentsRoute
  DashSettingsRoute: typeof DashSettingsRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAlertsRoute: DashAlertsRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashIncidentsRoute: DashIncidentsRoute,
  DashSettingsRoute: DashSettingsRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
